#!/usr/bin/env python3
"""Generate the small Lean data module from the canonical JSON certificate.

The certificate version, Cartan and root coordinates, highest-root candidate,
reflection permutations, and six orbit seeds cross this boundary. The file
digest and simple-root index are derived during generation. Expected theorem
counts are deliberately stated in Lean source, not copied from JSON, so
changing a claimed count cannot make the checker pass.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CERTIFICATE = REPO_ROOT / "verification" / "certificates" / "e6_extrema_certificate.json"
DEFAULT_OUTPUT = REPO_ROOT / "CubicAnomaly" / "E6" / "Data.lean"


def lean_array(items: list[str]) -> str:
    return "#[" + ", ".join(items) + "]"


def lean_int(value: int) -> str:
    return str(value) if value >= 0 else f"({value})"


def int_array(values: list[int]) -> str:
    return lean_array([lean_int(value) for value in values])


def nat_array(values: list[int]) -> str:
    if any(value < 0 for value in values):
        raise ValueError("natural-number array contains a negative value")
    return lean_array([str(value) for value in values])


def mask(one_based_indices: list[int], root_count: int) -> int:
    if (not isinstance(one_based_indices, list)
            or any(type(index) is not int for index in one_based_indices)):
        raise ValueError("subsystem indices must be integers")
    if len(set(one_based_indices)) != len(one_based_indices):
        raise ValueError("subsystem root indices are not unique")
    if not all(1 <= index <= root_count for index in one_based_indices):
        raise ValueError("subsystem root index lies outside the root table")
    return sum(1 << (index - 1) for index in one_based_indices)


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def integer_rows(value, rows, columns, label):
    if (not isinstance(value, list) or len(value) != rows
            or any(not isinstance(row, list) or len(row) != columns
                   or any(type(entry) is not int for entry in row) for row in value)):
        raise ValueError(f"expected an integer {rows} by {columns} {label}")


def render_bytes(raw: bytes) -> str:
    """Translate exact certificate bytes; never interpolate untyped JSON into Lean."""
    certificate = json.loads(raw, object_pairs_hook=unique_object)
    certificate_version = certificate.get("certificate_version")
    if type(certificate_version) is not int or certificate_version != 8:
        raise ValueError("expected certificate_version 8")

    roots = certificate["roots"]
    cartan = certificate["cartan_matrix"]
    reflections = certificate["simple_reflection_permutations"]
    representatives = certificate["cell_representatives"]
    integer_rows(roots, 72, 6, "root table")
    integer_rows(cartan, 6, 6, "Cartan matrix")
    integer_rows(reflections, 6, 72, "reflection table")
    integer_rows([certificate["highest_root_coefficients"]], 1, 6, "highest root")
    if len({tuple(root) for root in roots}) != 72:
        raise ValueError("duplicate root coordinates")
    if any(sorted(row) != list(range(1, 73)) for row in reflections):
        raise ValueError("reflection row is not a permutation of the root indices")
    if not isinstance(representatives, list) or len(representatives) != 6:
        raise ValueError("expected six cell representatives")

    root_count = len(roots)
    zero_based_reflections = [[index - 1 for index in row] for row in reflections]
    simple_root = [1, 0, 0, 0, 0, 0]
    try:
        simple_root_index = roots.index(simple_root)
    except ValueError as error:
        raise ValueError("first Bourbaki simple root missing from certificate") from error

    seeds = []
    for representative in representatives:
        seeds.append(
            "{ d := %d, a := %d, theta := %d }"
            % (
                mask(representative["D_root_indices"], root_count),
                mask(representative["A_root_indices"], root_count),
                mask(representative["Theta_root_indices"], root_count),
            )
        )

    digest = hashlib.sha256(raw).hexdigest()
    root_rows = ",\n  ".join(int_array(row) for row in roots)
    reflection_rows = ",\n  ".join(nat_array(row) for row in zero_based_reflections)
    cartan_rows = ",\n  ".join(int_array(row) for row in cartan)
    seed_rows = ",\n  ".join(seeds)

    return f'''/-
This file is generated by formal/scripts/generate_lean_data.py.
Source: verification/certificates/e6_extrema_certificate.json
SHA-256: {digest}

Do not edit this file by hand.  The checker intentionally keeps all expected
cardinalities and theorem statements outside this generated module.
-/
import CubicAnomaly.E6.Types

namespace CubicAnomaly.E6.Data

def certificateVersion : Nat := {certificate_version}
def certificateSha256 : String := "{digest}"
def simpleRootIndex : Nat := {simple_root_index}

def cartan : Array (Array Int) := #[
  {cartan_rows}
]

def highestRoot : Array Int := {int_array(certificate['highest_root_coefficients'])}

def roots : Array (Array Int) := #[
  {root_rows}
]

def simpleReflections : Array (Array Nat) := #[
  {reflection_rows}
]

def cellSeeds : Array Triple := #[
  {seed_rows}
]

end CubicAnomaly.E6.Data
'''


def render(certificate_path: Path) -> str:
    return render_bytes(certificate_path.read_bytes())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--certificate", type=Path, default=DEFAULT_CERTIFICATE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    content = render(arguments.certificate)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_bytes(content.encode("utf-8"))  # LF on every platform


if __name__ == "__main__":
    main()
