import Mathlib

/-!
# Finite exceptional toral census

This module reconstructs the roots of `G2`, `F4`, `E6`, `E7`, and `E8` from
their Cartan matrices.  It then exhausts every root-lattice functional modulo
two and three, modulo the Weyl action generated by the simple reflections.

For order three, it retains exactly the rows whose grade-zero roots have full
rank and whose grade-one root graph is connected.  It also computes the
restriction of the grade-one trace cubic to each grade-zero simple factor.

The calculation is independent of the paper's six-row and cubic-index tables.
It formalizes the finite exceptional census, not the manuscript theorem that
the homogeneous hypotheses reduce to this census.  Likewise, the final
Cartan-restriction calculation still relies on the manuscript's invariant-
theory argument to identify a vanishing simple factor with a radical ideal.
-/

namespace CubicAnomaly.Classification.Exceptional

abbrev RootCoordinates := Array Int
abbrev Grading := Array Int

structure RootDatum where
  cartan : Array (Array Int)
  symmetrizer : Array Int

def g2Datum : RootDatum := {
  cartan := #[#[2, -1], #[-3, 2]]
  symmetrizer := #[1, 3]
}

def f4Datum : RootDatum := {
  cartan := #[
    #[2, -1, 0, 0],
    #[-1, 2, -2, 0],
    #[0, -1, 2, -1],
    #[0, 0, -1, 2]
  ]
  symmetrizer := #[2, 2, 1, 1]
}

def e6Datum : RootDatum := {
  cartan := #[
    #[2, 0, -1, 0, 0, 0],
    #[0, 2, 0, -1, 0, 0],
    #[-1, 0, 2, -1, 0, 0],
    #[0, -1, -1, 2, -1, 0],
    #[0, 0, 0, -1, 2, -1],
    #[0, 0, 0, 0, -1, 2]
  ]
  symmetrizer := #[1, 1, 1, 1, 1, 1]
}

def e7Datum : RootDatum := {
  cartan := #[
    #[2, 0, -1, 0, 0, 0, 0],
    #[0, 2, 0, -1, 0, 0, 0],
    #[-1, 0, 2, -1, 0, 0, 0],
    #[0, -1, -1, 2, -1, 0, 0],
    #[0, 0, 0, -1, 2, -1, 0],
    #[0, 0, 0, 0, -1, 2, -1],
    #[0, 0, 0, 0, 0, -1, 2]
  ]
  symmetrizer := #[1, 1, 1, 1, 1, 1, 1]
}

def e8Datum : RootDatum := {
  cartan := #[
    #[2, 0, -1, 0, 0, 0, 0, 0],
    #[0, 2, 0, -1, 0, 0, 0, 0],
    #[-1, 0, 2, -1, 0, 0, 0, 0],
    #[0, -1, -1, 2, -1, 0, 0, 0],
    #[0, 0, 0, -1, 2, -1, 0, 0],
    #[0, 0, 0, 0, -1, 2, -1, 0],
    #[0, 0, 0, 0, 0, -1, 2, -1],
    #[0, 0, 0, 0, 0, 0, -1, 2]
  ]
  symmetrizer := #[1, 1, 1, 1, 1, 1, 1, 1]
}

private def indices (n : Nat) : List Nat := List.range n

private def simpleRoot (rank index : Nat) : RootCoordinates :=
  (indices rank).map (fun j => if j = index then 1 else 0) |>.toArray

private def negRoot (root : RootCoordinates) : RootCoordinates :=
  root.map (fun coordinate => -coordinate)

private def addRoot
    (left right : RootCoordinates) : RootCoordinates :=
  (indices left.size).map (fun i => left[i]! + right[i]!) |>.toArray

private def reflectRoot
    (datum : RootDatum) (root : RootCoordinates) (simple : Nat) :
    RootCoordinates :=
  let coefficient := (indices datum.cartan.size).foldl
    (fun total j => total + root[j]! * (datum.cartan[j]!)[simple]!) 0
  (indices datum.cartan.size).map (fun j =>
    if j = simple then root[j]! - coefficient else root[j]!) |>.toArray

private def closure {α : Type} [BEq α] [Hashable α] [Inhabited α]
    (next : α → Array α) (seeds : Array α) : Array α := Id.run do
  let mut seen : Std.HashSet α := Std.HashSet.emptyWithCapacity 256
  let mut queue : Array α := #[]
  for seed in seeds do
    if !seen.contains seed then
      seen := seen.insert seed
      queue := queue.push seed
  let mut cursor := 0
  while cursor < queue.size do
    let current := queue[cursor]!
    cursor := cursor + 1
    for image in next current do
      if !seen.contains image then
        seen := seen.insert image
        queue := queue.push image
  return queue

/-- Generate a finite exceptional root system from its simple roots. -/
def roots (datum : RootDatum) : Array RootCoordinates :=
  let rank := datum.cartan.size
  let seeds := (Array.range rank).foldl (fun acc i =>
    let root := simpleRoot rank i
    (acc.push root).push (negRoot root)) #[]
  closure (fun root =>
    (Array.range rank).map (reflectRoot datum root)) seeds

private def assignments : Nat → Nat → Array Grading
  | 0, _ => #[#[]]
  | rank + 1, modulus =>
      (assignments rank modulus).foldl (fun acc xs =>
        (Array.range modulus).foldl (fun output value =>
          output.push (xs.push (Int.ofNat value))) acc) #[]

private def gradingReflectMod
    (datum : RootDatum) (modulus : Int) (grading : Grading)
    (simple : Nat) : Grading :=
  (Array.range datum.cartan.size).map fun j =>
    (grading[j]! - (datum.cartan[j]!)[simple]! * grading[simple]!) % modulus

private def gradingOrbitMod
    (datum : RootDatum) (modulus : Int) (grading : Grading) : Array Grading :=
  closure (fun current =>
    (Array.range datum.cartan.size).map
      (gradingReflectMod datum modulus current)) #[grading]

private def gradeMod
    (modulus : Int) (root : RootCoordinates) (grading : Grading) : Int :=
  ((indices root.size).foldl
    (fun total i => total + root[i]! * grading[i]!) 0) % modulus

private def rowPivot (row : Array Int) : Option Nat :=
  (indices row.size).find? fun i => row[i]! != 0

/-- Fraction-free integer Gaussian rank. -/
def vectorRank (vectors : Array RootCoordinates) : Nat := Id.run do
  let mut basis : Array RootCoordinates := #[]
  for vector in vectors do
    let mut row := vector
    for old in basis do
      if let some pivot := rowPivot old then
        let oldPivot := old[pivot]!
        let rowPivotValue := row[pivot]!
        if rowPivotValue != 0 then
          row := (Array.range row.size).map fun j =>
            oldPivot * row[j]! - rowPivotValue * old[j]!
    if (rowPivot row).isSome then
      basis := basis.push row
  return basis.size

private def inner
    (datum : RootDatum) (left right : RootCoordinates) : Int :=
  (indices datum.cartan.size).foldl (fun outer i =>
    (indices datum.cartan.size).foldl (fun total j =>
      total + left[i]! * (datum.cartan[i]!)[j]! *
        datum.symmetrizer[j]! * right[j]!) outer) 0

private def rootComponents
    (datum : RootDatum) (system : Array RootCoordinates) :
    Array (Array RootCoordinates) := Id.run do
  let mut seen : Std.HashSet RootCoordinates :=
    Std.HashSet.emptyWithCapacity system.size
  let mut components : Array (Array RootCoordinates) := #[]
  for seed in system do
    if !seen.contains seed then
      seen := seen.insert seed
      let mut queue := #[seed]
      let mut component : Array RootCoordinates := #[]
      let mut cursor := 0
      while cursor < queue.size do
        let current := queue[cursor]!
        cursor := cursor + 1
        component := component.push current
        for candidate in system do
          if !seen.contains candidate && inner datum current candidate != 0 then
            seen := seen.insert candidate
            queue := queue.push candidate
      components := components.push component
  return components

private def gradeOneConnected
    (gradeOne gradeZero : Array RootCoordinates) : Bool := Id.run do
  if gradeOne.isEmpty then return false
  let oneSet := Std.HashSet.ofList gradeOne.toList
  let mut seen : Std.HashSet RootCoordinates :=
    Std.HashSet.emptyWithCapacity gradeOne.size
  let mut queue := #[gradeOne[0]!]
  seen := seen.insert gradeOne[0]!
  let mut cursor := 0
  while cursor < queue.size do
    let current := queue[cursor]!
    cursor := cursor + 1
    for alpha in gradeZero do
      let image := addRoot current alpha
      if oneSet.contains image && !seen.contains image then
        seen := seen.insert image
        queue := queue.push image
  return seen.size = gradeOne.size

structure ToralSignature where
  gradeZeroRoots : Nat
  gradeOneRoots : Nat
  /-- Sorted `(root count, lattice rank)` pairs for the grade-zero components. -/
  componentRootCountRanks : Array (Nat × Nat)
deriving BEq, Hashable, Repr, DecidableEq

private def componentSignatureLE
    (left right : Nat × Nat) : Bool :=
  decide (left.1 < right.1 ∨ (left.1 = right.1 ∧ left.2 ≤ right.2))

private def componentSignatureSort
    (items : Array (Nat × Nat)) : Array (Nat × Nat) :=
  items.foldl (fun sorted value =>
    let before := sorted.takeWhile (fun old => componentSignatureLE old value)
    let after := sorted.drop before.size
    (before.push value) ++ after) #[]

private def signature
    (datum : RootDatum) (gradeZero gradeOne : Array RootCoordinates) :
    ToralSignature :=
  let components := rootComponents datum gradeZero
  {
    gradeZeroRoots := gradeZero.size
    gradeOneRoots := gradeOne.size
    componentRootCountRanks := componentSignatureSort
      (components.map fun component => (component.size, vectorRank component))
  }

/--
All full-rank order-three rows with equal grade-one/grade-two dimensions and a
connected grade-one root graph, modulo the generated Weyl action.
-/
def fullRankOrderThreeSignatures (datum : RootDatum) : Array ToralSignature :=
    Id.run do
  let system := roots datum
  let mut gradingSeen : Std.HashSet Grading :=
    Std.HashSet.emptyWithCapacity 7000
  let mut output : Array ToralSignature := #[]
  for grading in assignments datum.cartan.size 3 do
    if grading.any (fun value => value != 0) &&
        !gradingSeen.contains grading then
      let orbit := gradingOrbitMod datum 3 grading
      for image in orbit do
        gradingSeen := gradingSeen.insert image
      let gradeZero := system.filter fun root => gradeMod 3 root grading = 0
      if vectorRank gradeZero = datum.cartan.size then
        let gradeOne := system.filter fun root => gradeMod 3 root grading = 1
        let gradeTwo := system.filter fun root => gradeMod 3 root grading = 2
        if gradeOne.size = gradeTwo.size &&
            gradeOneConnected gradeOne gradeZero then
          output := output.push (signature datum gradeZero gradeOne)
  return output

/-- Every full-rank inner involutive row has a connected odd-root graph. -/
def fullRankOrderTwoRowsConnected (datum : RootDatum) : Bool := Id.run do
  let system := roots datum
  let mut gradingSeen : Std.HashSet Grading :=
    Std.HashSet.emptyWithCapacity 512
  for grading in assignments datum.cartan.size 2 do
    if grading.any (fun value => value != 0) &&
        !gradingSeen.contains grading then
      let orbit := gradingOrbitMod datum 2 grading
      for image in orbit do
        gradingSeen := gradingSeen.insert image
      let gradeZero := system.filter fun root => gradeMod 2 root grading = 0
      if vectorRank gradeZero = datum.cartan.size then
        let gradeOne := system.filter fun root => gradeMod 2 root grading = 1
        if !gradeOneConnected gradeOne gradeZero then return false
  return true

private def expectedSignature
    (gradeZero gradeOne : Nat)
    (componentRootCountRanks : Array (Nat × Nat)) : ToralSignature := {
  gradeZeroRoots := gradeZero
  gradeOneRoots := gradeOne
  componentRootCountRanks := componentRootCountRanks
}

/--
The complete exceptional full-rank order-three census, identified by the
root count and lattice rank of each grade-zero component.
-/
theorem exceptional_toral_census :
    (roots g2Datum).size = 12 ∧
    (roots f4Datum).size = 48 ∧
    (roots e6Datum).size = 72 ∧
    (roots e7Datum).size = 126 ∧
    (roots e8Datum).size = 240 ∧
    fullRankOrderThreeSignatures g2Datum =
      #[expectedSignature 6 3 #[(6, 2)]] ∧
    fullRankOrderThreeSignatures f4Datum =
      #[expectedSignature 12 18 #[(6, 2), (6, 2)]] ∧
    fullRankOrderThreeSignatures e6Datum =
      #[expectedSignature 18 27 #[(6, 2), (6, 2), (6, 2)]] ∧
    fullRankOrderThreeSignatures e7Datum =
      #[expectedSignature 36 45 #[(6, 2), (30, 5)]] ∧
    fullRankOrderThreeSignatures e8Datum = #[
      expectedSignature 78 81 #[(6, 2), (72, 6)],
      expectedSignature 72 84 #[(72, 8)]
    ] := by
  native_decide

/-- The finite order-two branch used by the complex-type exclusion. -/
theorem exceptional_order_two_odd_graphs_connected :
    fullRankOrderTwoRowsConnected g2Datum = true ∧
    fullRankOrderTwoRowsConnected f4Datum = true ∧
    fullRankOrderTwoRowsConnected e6Datum = true ∧
    fullRankOrderTwoRowsConnected e7Datum = true ∧
    fullRankOrderTwoRowsConnected e8Datum = true := by
  native_decide

private def onSimpleCoroot
    (datum : RootDatum) (weight : RootCoordinates) (simple : Nat) : Int :=
  (indices datum.cartan.size).foldl
    (fun total j => total + weight[j]! * (datum.cartan[j]!)[simple]!) 0

private def onRootCoroot
    (datum : RootDatum) (weight root : RootCoordinates) : Int :=
  (2 * inner datum weight root) / inner datum root root

private def rootPairingsIntegral (datum : RootDatum) : Bool :=
  let system := roots datum
  system.all fun weight => system.all fun root =>
    (2 * inner datum weight root) % inner datum root root = 0

private def cubicContraction
    (datum : RootDatum) (one : Array RootCoordinates)
    (beta : RootCoordinates) (i j : Nat) : Int :=
  one.foldl (fun total weight =>
    total + onRootCoroot datum weight beta *
      onSimpleCoroot datum weight i * onSimpleCoroot datum weight j) 0

private def componentCartanCubicZero
    (datum : RootDatum) (one component : Array RootCoordinates) : Bool :=
  component.all fun beta =>
    (Array.range datum.cartan.size).all fun i =>
      (Array.range datum.cartan.size).all fun j =>
        cubicContraction datum one beta i j = 0

structure CubicSignature where
  row : ToralSignature
  /-- Sorted `(root count, lattice rank)` pairs for the cubic-null components. -/
  cartanCubicNullRootCountRanks : Array (Nat × Nat)
deriving BEq, Repr, DecidableEq

private def cubicSignature
    (datum : RootDatum) (gradeZero gradeOne : Array RootCoordinates) :
    CubicSignature :=
  let cubicNull := (rootComponents datum gradeZero).filter
    (componentCartanCubicZero datum gradeOne)
  {
    row := signature datum gradeZero gradeOne
    cartanCubicNullRootCountRanks := componentSignatureSort
      (cubicNull.map fun component => (component.size, vectorRank component))
  }

/-- Add the exact grade-one trace-cubic restriction to each census row. -/
def fullRankOrderThreeCubicSignatures
    (datum : RootDatum) : Array CubicSignature := Id.run do
  let system := roots datum
  let mut gradingSeen : Std.HashSet Grading :=
    Std.HashSet.emptyWithCapacity 7000
  let mut output : Array CubicSignature := #[]
  for grading in assignments datum.cartan.size 3 do
    if grading.any (fun value => value != 0) &&
        !gradingSeen.contains grading then
      let orbit := gradingOrbitMod datum 3 grading
      for image in orbit do
        gradingSeen := gradingSeen.insert image
      let gradeZero := system.filter fun root => gradeMod 3 root grading = 0
      if vectorRank gradeZero = datum.cartan.size then
        let gradeOne := system.filter fun root => gradeMod 3 root grading = 1
        let gradeTwo := system.filter fun root => gradeMod 3 root grading = 2
        if gradeOne.size = gradeTwo.size &&
            gradeOneConnected gradeOne gradeZero then
          output := output.push (cubicSignature datum gradeZero gradeOne)
  return output

private def expectedCubicSignature
    (row : ToralSignature)
    (componentRootCountRanks : Array (Nat × Nat)) : CubicSignature := {
  row := row
  cartanCubicNullRootCountRanks := componentRootCountRanks
}

/--
The grade-one Cartan trace cubic vanishes on exactly the rank-six, 72-root
component of the `E8` row with component signatures `(6,2)` and `(72,6)`.
-/
theorem cartan_cubic_selector :
    rootPairingsIntegral g2Datum = true ∧
    rootPairingsIntegral f4Datum = true ∧
    rootPairingsIntegral e6Datum = true ∧
    rootPairingsIntegral e7Datum = true ∧
    rootPairingsIntegral e8Datum = true ∧
    fullRankOrderThreeCubicSignatures g2Datum = #[
      expectedCubicSignature
        (expectedSignature 6 3 #[(6, 2)]) #[]
    ] ∧
    fullRankOrderThreeCubicSignatures f4Datum = #[
      expectedCubicSignature
        (expectedSignature 12 18 #[(6, 2), (6, 2)]) #[]
    ] ∧
    fullRankOrderThreeCubicSignatures e6Datum = #[
      expectedCubicSignature
        (expectedSignature 18 27 #[(6, 2), (6, 2), (6, 2)]) #[]
    ] ∧
    fullRankOrderThreeCubicSignatures e7Datum = #[
      expectedCubicSignature
        (expectedSignature 36 45 #[(6, 2), (30, 5)]) #[]
    ] ∧
    fullRankOrderThreeCubicSignatures e8Datum = #[
      expectedCubicSignature
        (expectedSignature 78 81 #[(6, 2), (72, 6)]) #[(72, 6)],
      expectedCubicSignature
        (expectedSignature 72 84 #[(72, 8)]) #[]
    ] := by
  native_decide

end CubicAnomaly.Classification.Exceptional
